name: build and sonarqube 
on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - 'DCOS/**'
      - 'K8s/**'
      - 'load-gen/**'
      - 'OpenShift/**'
      - 'Swarm/**'
  pull_request:
    types: [opened, synchronize, reopened]


jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION=true 
    steps:
      - uses: actions/checkout@v4
      - name: Run a Node.js script
        run: node -v
   #code checkout
      - uses: actions/checkout@v4.3.1
      - name: Build the stack
        run: docker compose build
    #sonarqube analysis:
  SonarQube:
      runs-on: ubuntu-latest
      needs: build
      steps:  
      - uses: actions/checkout@v4.3.1 # v4.3.1
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6 # v6.0.0
        env:
          SONAR_TOKEN: ${{secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{secrets.SONAR_HOST_URL}}
      #docker image build 
      - name: Build docker image
        run: docker build -t $GITHUB_SHA .
      #docker image push
      - name: Push docker image
        run: echo ${{secrets.DOCKER_PASSWORD}} |  docker Login -u ${{secrets.DOCKER_USERNAME}} --password-stdin && docker push $GITHUN_SHA